#!/usr/bin/perl -w
use Tk;
use Tk::LabFrame;
use Storable;
use Math::Trig;
use Math::BigFloat;
Math::BigFloat->precision(-4);

my $mw = MainWindow->new;

$Profile_Length = 10;
$Profile_RelativeOrientation = 0;
$Profile_Side1 = "notch";
$Profile_Side2 = "disable";
$Side1_BranchDiamter = 1.750;
$Side1_HeaderDiamter = 1.750;
$Side1_BranchWallThickness = 0.120;
$Side1_BranchMateAngle = 90;
$Side2_BranchDiamter = 1.750;
$Side2_HeaderDiamter = 1.750;
$Side2_BranchWallThickness = 0.120;
$Side2_BranchMateAngle = 90;
$Parameters_Filename = "/home/cnc/Desktop/Post/notch.ngc";
$Parameters_Feedrate = 15;
$Parameters_PierceHeight = 0.160;
$Parameters_PierceDelay = 0.8;
$Parameters_CutHeight = 0.150;
$Parameters_ZRetract = 0.375;
$Parameters_PostDelay = 2;
$DataFile = "/tmp/.NotchMaster";
$Parameters_TestRun = "no";
$Parameters_YHome = 20;


sub storeData
{
  if (open(my $fh, '>:encoding(UTF-8)', $DataFile))
  {
    print $fh "$Profile_Length\n";
    print $fh "$Profile_RelativeOrientation\n";
    print $fh "$Profile_Side1\n";
    print $fh "$Profile_Side2\n";
    print $fh "$Side1_BranchDiamter\n";
    print $fh "$Side1_HeaderDiamter\n";
    print $fh "$Side1_BranchWallThickness\n";
    print $fh "$Side1_BranchMateAngle\n";
    print $fh "$Side2_BranchDiamter\n";
    print $fh "$Side2_HeaderDiamter\n";
    print $fh "$Side2_BranchWallThickness\n";
    print $fh "$Side2_BranchMateAngle\n";
    print $fh "$Parameters_Filename\n";
    print $fh "$Parameters_PierceHeight\n";
    print $fh "$Parameters_PierceDelay\n";
    print $fh "$Parameters_CutHeight\n";
    print $fh "$Parameters_ZRetract\n";
    print $fh "$Parameters_PostDelay\n";
    print $fh "$Parameters_Feedrate\n";
    print $fh "$Parameters_YHome\n";
    close($fh);
  }
  else
  {
    print "Can't store data!";
  }
}
sub fetchData
{
  if (open(my $fh, '<:encoding(UTF-8)', $DataFile))
  {
    $Profile_Length = <$fh>;
    $Profile_RelativeOrientation = <$fh>;
    $Profile_Side1 = <$fh>;
    $Profile_Side2 = <$fh>;
    $Side1_BranchDiamter = <$fh>;
    $Side1_HeaderDiamter = <$fh>;
    $Side1_BranchWallThickness = <$fh>;
    $Side1_BranchMateAngle = <$fh>;
    $Side2_BranchDiamter = <$fh>;
    $Side2_HeaderDiamter = <$fh>;
    $Side2_BranchWallThickness = <$fh>;
    $Side2_BranchMateAngle = <$fh>;
    $Parameters_Filename = <$fh>;
    $Parameters_PierceHeight = <$fh>;
    $Parameters_PierceDelay = <$fh>;
    $Parameters_CutHeight = <$fh>;
    $Parameters_ZRetract = <$fh>;
    $Parameters_PostDelay = <$fh>;
    $Parameters_Feedrate = <$fh>;
    $Parameters_YHome = <$fh>;
    close($fh);

    chomp $Profile_Length;
    chomp $Profile_RelativeOrientation;
    chomp $Profile_Side1;
    chomp $Profile_Side2;
    chomp $Side1_BranchDiamter;
    chomp $Side1_HeaderDiamter;
    chomp $Side1_BranchWallThickness;
    chomp $Side1_BranchMateAngle;
    chomp $Side2_BranchDiamter;
    chomp $Side2_HeaderDiamter;
    chomp $Side2_BranchWallThickness;
    chomp $Side2_BranchMateAngle;
    chomp $Parameters_Filename;
    chomp $Parameters_PierceHeight;
    chomp $Parameters_PierceDelay;
    chomp $Parameters_CutHeight;
    chomp $Parameters_ZRetract;
    chomp $Parameters_PostDelay;
    chomp $Parameters_Feedrate;
    chomp $Parameters_YHome;
  }
  else
  {
    #print "Can't fetch data!";
  }
}
sub degree_sine {
    my $degrees = shift;
    my $radians = deg2rad($degrees);
    my $result = sin($radians);

    return $result;
}
sub degree_cosine {
    my $degrees = shift;
    my $radians = deg2rad($degrees);
    my $result = cos($radians);

    return $result;
}
sub degree_tangent {
    my $degrees = shift;
    my $radians = deg2rad($degrees);
    my $result = tan($radians);

    return $result;
}
sub Gcode_CalculateNotch
{
  $Branch_Diamter = shift;
  $Header_Diameter = shift;
  $Wall_Thickness = shift;
  $Angle = shift;

  my $GcodeBlock = "";
  my $Awords = "";
  my $Ywords = "";

  $RO = $Branch_Diamter / 2;
  $RU = $Header_Diameter / 2;
  $RI = $RO - $Wall_Thickness;
  $AF = $Angle;
  $ID = 0;
  $A_Axis_Angle = 2;
  for (my $i=0; $i < 180; $i++)
  {
    $Y = sqrt($RU **2 - (($RI * degree_sine($ID)) **2)) / degree_sine($AF) - degree_tangent(90 - $AF) * $RI * degree_cosine($ID);
    $Y = $Y * -1;
    $ID=$ID + 2;
    $A_Axis_Angle = $A_Axis_Angle + 2;
  	#300=[#300+2]

    $Ysimple = Math::BigFloat->new($Y);
    #$GcodeBlock .= "G1 A$A_Axis_Angle Y$Ysimple F$Parameters_Feedrate\n";
    $Awords .= "$A_Axis_Angle\n";
    $Ywords .= "$Ysimple\n";
  }
  $smallestY = 100; #Big default, lower the value as we see smaller ones
  my @lines = split /\n/, $Ywords;
  foreach my $line (@lines)
  {
    chomp $line;
    if ($line < $smallestY)
    {
      $smallestY = $line;
    }
  }
  #print "Offset is $smallestY\n"; #Works!
  my @Yword_lines = split /\n/, $Ywords;
  #my @Aword_lines = split /\n/, $Awords; #Returns 2 degree increments to 360
  for( $i = 0; $i < @Yword_lines; $i++ )
  {
    $Yoffset = $Yword_lines[$i] - $smallestY;
   #print "Y$Yoffset\n";
   $GcodeBlock .= "$Yoffset\n";
  }
  return $GcodeBlock;
}

sub postGcode
{
  $Parameters_Touchoff = "G0 Z$Parameters_CutHeight";
  if ($Parameters_TestRun eq "no")
  {
    $Parameters_Touchoff = "o<touchoff> call [$Parameters_PierceHeight] [$Parameters_PierceDelay] [$Parameters_CutHeight]"
  }
  if ($Profile_Side1 eq "notch" && $Profile_Side2 eq "disable")
  {
    $Yoffsets = Gcode_CalculateNotch($Side1_BranchDiamter, $Side1_HeaderDiamter, $Side1_BranchWallThickness, $Side1_BranchMateAngle);
    $mw->messageBox(-title => 'Post', -message => 'Posting with Side 1 notch and Side 2 Disabled!', -type => 'ok', -default => 'ok');
    my @Gcode_lines = split /\n/, $Yoffsets;
    $A_word = 2;

    if (open(my $fh, '>:encoding(UTF-8)', $Parameters_Filename))
    {
      print $fh "G20\nG64 P0.001\n";
      print $fh "G0 A$A_word Y$Gcode_lines[0]\n\n";
      print $fh "$Parameters_Touchoff\n";
      for( $i = 1; $i < @Gcode_lines; $i++ )
      {
        $A_word += 2;
        if ($A_word >= 360)
        {
          $A_word = $A_word - 360;
        }
        chomp $Gcode_lines[$i];
        $Y = Math::BigFloat->new($Gcode_lines[$i]);
        print $fh "G1 A$A_word Y$Y F$Parameters_Feedrate\n";
      }
      print $fh "\nM5\nG4 P$Parameters_PostDelay\nG0 Z$Parameters_ZRetract\n";
      print $fh "G0 Y$Parameters_YHome\nM30\n";
      close($fh);
    }
    else
    {
      $mw->messageBox(-title => 'Post', -message => 'Could not write file!', -type => 'ok', -default => 'ok');
    }
    return;
  }
  elsif ($Profile_Side1 eq "notch" && $Profile_Side2 eq "slice")
  {
    $Yoffsets = Gcode_CalculateNotch($Side1_BranchDiamter, $Side1_HeaderDiamter, $Side1_BranchWallThickness, $Side1_BranchMateAngle);
    $mw->messageBox(-title => 'Post', -message => 'Posting with Side 1 Notch and Side 2 Slice!', -type => 'ok', -default => 'ok');
    my @Gcode_lines = split /\n/, $Yoffsets;
    $A_word = 2;

    if (open(my $fh, '>:encoding(UTF-8)', $Parameters_Filename))
    {
      #Post header
      print $fh "G20\nG64 P0.001\n";
      print $fh "G0 A$A_word Y$Gcode_lines[0]\n\n";

      #Post Side 1 Notch
      print $fh "$Parameters_Touchoff\n";
      for( $i = 1; $i < @Gcode_lines; $i++ )
      {
        $A_word += 2;
        if ($A_word >= 360)
        {
          $A_word = $A_word - 360;
        }
        chomp $Gcode_lines[$i];
        $Y = Math::BigFloat->new($Gcode_lines[$i]);
        print $fh "G1 A$A_word Y$Y F$Parameters_Feedrate\n";
      }
      print $fh "\nM5\nG4 P$Parameters_PostDelay\nG0 Z$Parameters_ZRetract\n";

      #Post Side 2 Slice
      #Feedrate in deg/min = Feedrate in inches/min / (branch diameter * pie) * 360
      $Feedrate_in_deg_min = Math::BigFloat->new($Parameters_Feedrate / ($Side1_BranchDiamter * 3.14) * 360);
      print $fh "G0 A-0 Y-$Profile_Length\n";
      print $fh "$Parameters_Touchoff\n";
      print $fh "G1 A180 F$Feedrate_in_deg_min\n";
      print $fh "G1 A0 F$Feedrate_in_deg_min\n";
      print $fh "\nM5\nG4 P$Parameters_PostDelay\nG0 Z$Parameters_ZRetract\n";
      print $fh "G0 Y$Parameters_YHome\nM30\n";
      close($fh);
    }
    else
    {
      $mw->messageBox(-title => 'Post', -message => 'Could not write file!', -type => 'ok', -default => 'ok');
    }
    return;
  }
  elsif ($Profile_Side1 eq "notch" && $Profile_Side2 eq "notch")
  {
    $Yoffsets = Gcode_CalculateNotch($Side1_BranchDiamter, $Side1_HeaderDiamter, $Side1_BranchWallThickness, $Side1_BranchMateAngle);
    $mw->messageBox(-title => 'Post', -message => 'Posting with Side 1 Notch and Side 2 Notch!', -type => 'ok', -default => 'ok');
    my @Gcode_lines = split /\n/, $Yoffsets;
    $A_word = 2;

    if (open(my $fh, '>:encoding(UTF-8)', $Parameters_Filename))
    {
      #Post header
      print $fh "G20\nG64 P0.001\n";
      print $fh "G0 A$A_word Y$Gcode_lines[0]\n\n";

      #Post Side 1 Notch
      print $fh "$Parameters_Touchoff\n";
      for( $i = 1; $i < @Gcode_lines; $i++ )
      {
        $A_word += 2;
        if ($A_word >= 360)
        {
          $A_word = $A_word - 360;
        }
        chomp $Gcode_lines[$i];
        $Y = Math::BigFloat->new($Gcode_lines[$i]);
        print $fh "G1 A$A_word Y$Y F$Parameters_Feedrate\n";
      }
      print $fh "\nM5\nG4 P$Parameters_PostDelay\nG0 Z$Parameters_ZRetract\n";

      #Post Side 2 Notch
      $Yoffsets = Gcode_CalculateNotch($Side2_BranchDiamter, $Side2_HeaderDiamter, $Side2_BranchWallThickness, $Side2_BranchMateAngle);
      my @Gcode_lines = split /\n/, $Yoffsets;
      $A_word = 2 + $Profile_RelativeOrientation;
      if ($A_word >= 360)
      {
        $A_word = $A_word - 360;
      }
      $YStart = (Math::BigFloat->new($Gcode_lines[0]) * -1) - $Profile_Length;
      print $fh "G0 A$A_word Y$YStart\n\n";
      print $fh "$Parameters_Touchoff\n";
      for( $i = 1; $i < @Gcode_lines; $i++ )
      {
        $A_word += 2;
        if ($A_word >= 360)
        {
          $A_word = $A_word - 360;
        }
        chomp $Gcode_lines[$i];
        $Y = (Math::BigFloat->new($Gcode_lines[$i]) * -1) - $Profile_Length;
        print $fh "G1 A$A_word Y$Y F$Parameters_Feedrate\n";
      }
      print $fh "\nM5\nG4 P$Parameters_PostDelay\nG0 Z$Parameters_ZRetract\n";
      print $fh "G0 Y$Parameters_YHome\nM30\n";
      close($fh);
    }
    else
    {
      $mw->messageBox(-title => 'Post', -message => 'Could not write file!', -type => 'ok', -default => 'ok');
    }
    return;
  }
  $mw->messageBox(-title => 'Post', -message => 'Not Implemented Yet', -type => 'ok', -default => 'ok');
  return;
}

fetchData();

$mw->title("Xmotion NotchMaster");
#$mw->geometry ("900x600");
$profile_frame = $mw->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Profile', -labelside => 'acrosstop');
$profile_frame->Label(-text => "Tube Length")->pack(-side => 'top');
$profile_frame->Entry(-textvariable=>\$Profile_Length)->pack();
$profile_frame->Label(-text => "Relative Orientation Angle")->pack(-side => 'top');
$profile_frame->Entry(-textvariable=>\$Profile_RelativeOrientation)->pack();
$side1_radio = $profile_frame->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Side 1', -labelside => 'acrosstop');
foreach (qw/notch slice/) {
    $side1_radio->Radiobutton(-text => $_, -variable => \$Profile_Side1,
        -value => $_)->pack(-anchor => 'w');
}
$side1_radio->pack(-side => 'left');

$side2_radio = $profile_frame->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Side 2', -labelside => 'acrosstop');
foreach (qw/notch slice disable/) {
    $side2_radio->Radiobutton(-text => $_, -variable => \$Profile_Side2,
        -value => $_)->pack(-anchor => 'w');
}
$side2_radio->pack(-side => 'right');

$profile_frame->pack(-side => 'top');

$side1_frame = $mw->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Side 1', -labelside => 'acrosstop');
$side1_frame->Label(-text => "Branch Diameter")->pack(-side => 'top');
$side1_frame->Entry(-textvariable=>\$Side1_BranchDiamter)->pack();
$side1_frame->Label(-text => "Header Diameter")->pack(-side => 'top');
$side1_frame->Entry(-textvariable=>\$Side1_HeaderDiamter)->pack();
$side1_frame->Label(-text => "Branch Wall Thickness")->pack(-side => 'top');
$side1_frame->Entry(-textvariable=>\$Side1_BranchWallThickness)->pack();
$side1_frame->Label(-text => "Mate Angle")->pack(-side => 'top');
$side1_frame->Entry(-textvariable=>\$Side1_BranchMateAngle)->pack();
$side1_frame->pack(-side => 'left');

$side2_frame = $mw->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Side 2', -labelside => 'acrosstop');
$side2_frame->Label(-text => "Branch Diameter")->pack(-side => 'top');
$side2_frame->Entry(-textvariable=>\$Side2_BranchDiamter)->pack();
$side2_frame->Label(-text => "Header Diameter")->pack(-side => 'top');
$side2_frame->Entry(-textvariable=>\$Side2_HeaderDiamter)->pack();
$side2_frame->Label(-text => "Branch Wall Thickness")->pack(-side => 'top');
$side2_frame->Entry(-textvariable=>\$Side2_BranchWallThickness)->pack();
$side2_frame->Label(-text => "Mate Angle")->pack(-side => 'top');
$side2_frame->Entry(-textvariable=>\$Side2_BranchMateAngle)->pack();
$side2_frame->pack(-side => 'right');

$Paramaters_frame = $mw->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Parameters', -labelside => 'acrosstop');
$Paramaters_frame->Label(-text => "Filename")->pack(-side => 'top');
$Paramaters_frame->Entry(-textvariable=>\$Parameters_Filename)->pack();
$Paramaters_frame->Label(-text => "Pierce Height")->pack(-side => 'top');
$Paramaters_frame->Entry(-textvariable=>\$Parameters_PierceHeight)->pack();
$Paramaters_frame->Label(-text => "Pierce Delay")->pack(-side => 'top');
$Paramaters_frame->Entry(-textvariable=>\$Parameters_PierceDelay)->pack();
$Paramaters_frame->Label(-text => "Cut Height")->pack(-side => 'top');
$Paramaters_frame->Entry(-textvariable=>\$Parameters_CutHeight)->pack();
$Paramaters_frame->Label(-text => "Cut Feedrate")->pack(-side => 'top');
$Paramaters_frame->Entry(-textvariable=>\$Parameters_Feedrate)->pack();
$Paramaters_frame->Label(-text => "Z Retract Clearance")->pack(-side => 'top');
$Paramaters_frame->Entry(-textvariable=>\$Parameters_ZRetract)->pack();
$Paramaters_frame->Label(-text => "Post Cut Delay (Sec)")->pack(-side => 'top');
$Paramaters_frame->Entry(-textvariable=>\$Parameters_PostDelay)->pack();
$Paramaters_frame->Label(-text => "Y Home")->pack(-side => 'top');
$Paramaters_frame->Entry(-textvariable=>\$Parameters_YHome)->pack();
$button_frame = $Paramaters_frame->Frame(-borderwidth => 2, -relief => 'groove');
$button_frame->Button(-text => 'Quit', -command => sub { storeData(); exit; })->pack(-side => 'left');
$button_frame->Button(-text => 'Post Testrun', -command => sub { $Parameters_TestRun = "yes"; storeData(); postGcode(); })->pack(-side => 'right');
$button_frame->Button(-text => 'Post Cut', -command => sub { $Parameters_TestRun = "no"; storeData(); postGcode(); })->pack(-side => 'right');
$button_frame->pack;
$Paramaters_frame->pack(-side => 'bottom');

MainLoop;
