#!/bin/perl -w
use Tk;
use Tk::LabFrame;

my $mw = MainWindow->new;
$mw->title("NotchMaster");
#$mw->geometry ("900x600");
$profile_frame = $mw->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Profile', -labelside => 'acrosstop');
$profile_frame->Label(-text => "Tube Length")->pack(-side => 'top');
$profile_frame->Entry(-textvariable=>$Profile_Length)->pack();

$side1_radio = $profile_frame->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Side 1', -labelside => 'acrosstop');
foreach (qw/notch slice/) {
    $side1_radio->Radiobutton(-text => $_, -variable => \$Profile_Side1,
        -value => $_)->pack(-anchor => 'w');
}
$side1_radio->pack(-side => 'left');

$side2_radio = $profile_frame->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Side 2', -labelside => 'acrosstop');
foreach (qw/notch slice disable/) {
    $side2_radio->Radiobutton(-text => $_, -variable => \$Profile_Side2,
        -value => $_)->pack(-anchor => 'w');
}
$side2_radio->pack(-side => 'right');

$profile_frame->pack(-side => 'top');

$side1_frame = $mw->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Side 1', -labelside => 'acrosstop');
$side1_frame->Label(-text => "Branch Diameter")->pack(-side => 'top');
$side1_frame->Entry(-textvariable=>$Side1_BranchDiamter)->pack();
$side1_frame->Label(-text => "Header Diameter")->pack(-side => 'top');
$side1_frame->Entry(-textvariable=>$Side1_HeaderDiamter)->pack();
$side1_frame->Label(-text => "Branch Wall Thickness")->pack(-side => 'top');
$side1_frame->Entry(-textvariable=>$Side1_BranchWallThickness)->pack();
$side1_frame->Label(-text => "Mate Angle")->pack(-side => 'top');
$side1_frame->Entry(-textvariable=>$Side1_BranchMateAngle)->pack();
$side1_frame->pack(-side => 'left');

$side2_frame = $mw->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Side 2', -labelside => 'acrosstop');
$side2_frame->Label(-text => "Branch Diameter")->pack(-side => 'top');
$side2_frame->Entry(-textvariable=>$Side2_BranchDiamter)->pack();
$side2_frame->Label(-text => "Header Diameter")->pack(-side => 'top');
$side2_frame->Entry(-textvariable=>$Side2_HeaderDiamter)->pack();
$side2_frame->Label(-text => "Branch Wall Thickness")->pack(-side => 'top');
$side2_frame->Entry(-textvariable=>$Side2_BranchWallThickness)->pack();
$side2_frame->Label(-text => "Mate Angle")->pack(-side => 'top');
$side2_frame->Entry(-textvariable=>$Side2_BranchMateAngle)->pack();
$side2_frame->pack(-side => 'right');

$Paramaters_frame = $mw->LabFrame(-borderwidth => 2, -relief => 'groove', -label => 'Parameters', -labelside => 'acrosstop');
$Paramaters_frame->Label(-text => "Filename")->pack(-side => 'top');
$Paramaters_frame->Entry(-textvariable=>$Parameters_Filename)->pack();
$Paramaters_frame->Label(-text => "Feedrate")->pack(-side => 'top');
$Paramaters_frame->Entry(-textvariable=>$Parameters_Feedrate)->pack();
$button_frame = $Paramaters_frame->Frame(-borderwidth => 2, -relief => 'groove');
$button_frame->Button(-text => 'Quit', -command => sub { exit; })->pack(-side => 'left');
$button_frame->Button(-text => 'Post', -command => sub {  })->pack(-side => 'right');
$button_frame->pack;
$Paramaters_frame->pack(-side => 'bottom');

MainLoop;
