#!/usr/bin/perl -w

use Math::Trig;

$num_args = $#ARGV + 1;
if ($num_args != 5 ) {
    print "\nUsage: notch [#1 Branch Diameter] [#2 Header Diameter] [#3 Wall Thickness] [#4 Angle] [#5 Filename]\n";
    exit;
}

# (2) we got two command line args, so assume they are the
# first name and last name
$Branch_Diamter=$ARGV[0];
$Header_Diameter=$ARGV[1];
$Wall_Thickness=$ARGV[2];
$Angle=$ARGV[3];
$filename=$ARGV[4];

open($fh, '>', $filename) or die "Could not open file '$filename' $!";

sub degree_sine {
    my $degrees = shift;
    my $radians = deg2rad($degrees);
    my $result = sin($radians);

    return $result;
}
sub degree_cosine {
    my $degrees = shift;
    my $radians = deg2rad($degrees);
    my $result = cos($radians);

    return $result;
}
sub degree_tangent {
    my $degrees = shift;
    my $radians = deg2rad($degrees);
    my $result = tan($radians);

    return $result;
}

sub Gcode_Header()
{
  print $fh "G20\nG64 P0.001\n";
}
sub Gcode_NotchSpecifiedAngle
{
  my $angle = shift;
  $RO = $Branch_Diamter / 2;
  $RU = $Header_Diameter / 2;
  $RI = $RO - $Wall_Thickness;
  $AF = $Angle;
  $ID = 0;
  $A_Axis_Angle = 1;
  for (my $i=0; $i < $angle; $i++)
  {
    $Y = sqrt($RU **2 - (($RI * degree_sine($ID)) **2)) / degree_sine($AF) - degree_tangent(90 - $AF) * $RI * degree_cosine($ID);
    $ID=$ID + 1;
    $A_Axis_Angle = $A_Axis_Angle + 1;
  	#300=[#300+2]
    $Ysimple = sprintf("%.4f", $Y);  # 1.56

  }
  if ($angle == 1)
  {
    return "G0 A$A_Axis_Angle Y$Ysimple\nF50\n";
  }
  return "G1 A$A_Axis_Angle Y$Ysimple\n";
}
sub Gcode_NotchLoop()
{
  #100= #1   (Branch Diameter)
  #101= #2      (Header Diameter)
  #103= #3        ( Tube Thickness )
  #104= #4            (Joint ANGLE)

  #200 = [#100 / 2]         (RO)
  #201 = [#101 / 2]         (RU)
  #202 = [#200 - #103]  (RI)
  #203 = #104                (AF)
  #204 = 0                       (ID)
  #300= 2                       (A step in deg)
  #G0 A#300 Y[sqrt [#201 **2 - [ [#202 * sin [#204]] **2]] /  sin[#203] -  tan [90-#203] * #202 * cos[#204]]
	#204=[#204+2]
	#300=[#300+2]

  $RO = $Branch_Diamter / 2;
  $RU = $Header_Diameter / 2;
  $RI = $RO - $Wall_Thickness;
  $AF = $Angle;
  $ID = 0;
  $A_Axis_Angle = 2;
  for (my $i=0; $i < 180; $i++)
  {
    $Y = sqrt($RU **2 - (($RI * degree_sine($ID)) **2)) / degree_sine($AF) - degree_tangent(90 - $AF) * $RI * degree_cosine($ID);
    $ID=$ID + 2;
    $A_Axis_Angle = $A_Axis_Angle + 2;
  	#300=[#300+2]
    $Ysimple = sprintf("%.4f", $Y);  # 1.56
    print $fh "G0 A$A_Axis_Angle Y$Ysimple\n";
  }
}
sub Gcode_Footer()
{
  print $fh "M5\nM30\n";
}

print "Creating a notch at $Angle degrees with branch diameter of $Branch_Diamter and wall thickness of $Wall_Thickness to mate with a header diameter of $Header_Diameter!\n";

Gcode_Header();

Gcode_NotchLoop();

Gcode_Footer();
close $fh;
